project:
  type: website
  output-dir: _site
  resources:
    - CNAME

website:
  title: "Chris Johnston"
  site-url: "https://cdjohnston.com"
  sitemap: true
  navbar:
    left:
      - text: "About"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "CV"
        href: cv.qmd
  page-footer:
    right: "Built with [Quarto](https://quarto.org)."

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true
